version: '3.2'

services:
  domoticz:
    image: linuxserver/domoticz:latest
    container_name: domoticz
    depends_on:
      - zigbee
    environment:
      - PUID=1001
      - GUID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-label-raidfs/Containers/domoticz/domoticz:/config
    ports:
      - 10000:8080
      - 6144:6144
      - 1443:1443
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-label-raidfs/Containers/domoticz/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /srv/dev-disk-by-label-raidfs/Containers/domoticz/mosquitto/data:/mosquitto/data
      - /srv/dev-disk-by-label-raidfs/Containers/domoticz/mosquitto/log:/mosquitto/log
    ports:
      - 9001:9001
      - 1883:1883

  zigbee:
    depends_on:
      - mqtt
    image: koenkk/zigbee2mqtt
    container_name: zigbee
    restart: always
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-label-raidfs/Containers/domoticz/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
